config/routes.rb
Rails.application.routes.draw do
  resources :beta

   root 'pages#home'
   get "privacy" => "pages#privacy"

end

app/models/betum.rb
class Betum < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beta_controller.rb
class BetaController < ApplicationController
  before_action :set_betum, only: [:show, :edit, :update, :destroy]

  # GET /beta
  # GET /beta.json
  def index
    @beta = Betum.all
  end

  # GET /beta/1
  # GET /beta/1.json
  def show
  end

  # GET /beta/new
  def new
    @betum = Betum.new
  end

  # GET /beta/1/edit
  def edit
  end

  # POST /beta
  # POST /beta.json
  def create
    @betum = Betum.new(betum_params)

    respond_to do |format|
      if @betum.save
        format.html { redirect_to @betum, notice: 'Beta interest has been filed. Storyboard will follow up.' }
        format.json { render :show, status: :created, location: @betum }
      else
        format.html { render :new }
        format.json { render json: @betum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beta/1
  # PATCH/PUT /beta/1.json
  def update
    respond_to do |format|
      if @betum.update(betum_params)
        format.html { redirect_to @betum, notice: 'Betum was successfully updated.' }
        format.json { render :show, status: :ok, location: @betum }
      else
        format.html { render :edit }
        format.json { render json: @betum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beta/1
  # DELETE /beta/1.json
  def destroy
    @betum.destroy
    respond_to do |format|
      format.html { redirect_to beta_url, notice: 'Betum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_betum
      @betum = Betum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def betum_params
      params.require(:betum).permit(:name, :email, :expected_number_listeners, :plan)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beta_helper.rb
module BetaHelper
end

app/views/beta/_form.html.erb
<br> 

<%= form_for(@betum) do |f| %>
  <% if @betum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@betum.errors.count, "error") %> prohibited this betum from being saved:</h2>

      <ul>
      <% @betum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Name of Contact" %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, style: 'font-size: 20px', class: "form-control" %>
  </div>
  
  <div class="field">
    <%= f.label "How many listeners do you expect?" %><br>
    <%= f.text_field :expected_number_listeners, class: "form-control" %>
  </div>
    <div class="field">
    <%= f.label "Can you tell us anything about your team or how you would plan to podcast?" %><br>
    <%= f.text_field :plan, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "Apply for Beta", class: "btn btn-primary btn-lg" %>
  </div>
<% end %>

app/views/beta/edit.html.erb
<h1>Editing Betum</h1>

<%= render 'form' %>

<%= link_to 'Show', @betum %> |
<%= link_to 'Back', beta_path %>

app/views/beta/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Beta</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Expected number listeners</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beta.each do |betum| %>
      <tr>
        <td><%= betum.name %></td>
        <td><%= betum.email %></td>
        <td><%= betum.expected_number_listeners %></td>
        <td><%= betum.plan %></td>
        <td><%= link_to 'Show', betum %></td>
        <td><%= link_to 'Edit', edit_betum_path(betum) %></td>
        <td><%= link_to 'Destroy', betum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Betum', new_betum_path %>

app/views/beta/new.html.erb
<div class="containerform">


<h1 style="margin-top: 15px;">Register for Storyboard Beta</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

<br><br>
<p>We will follow up to provide information on the app and confirm that you would like to participate. Your email will not be shared or used for any other purpose, other than getting in touch with you about that beta.</p>

<br>

</div>

<br> 
    <section class="success" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                 <!-- <h2>About</h2> -->
                  <br>
                     <%= image_tag("Visualizer.png", class: "img-responsive middle") %>
                      <h2 style="color: white;">Why Storyboard?</h2> 
                     <hr class="star-light">
                </div>

                <div class="col-md-6">
                     <h2><b>Podcasting for Teams</b></h2> <p>25% of Americans are now regularly listening to podcasts. However, teams and companies still largely communicate over email, where competition for attention is fierce. Want to make a podcast for your team but keep it private? Storyboard makes this easy.</p>
                </div>
                <div class="col-md-6">
                  <h2><b>Easy Listening</b></h2>
                    <p>For your listeners, they will simply download the Storyboard App after receiving a verification code when you register. After we confirm the listener, they can download your episodes to listen in the car, on a flight, or wherever they enjoy listening to podcasts.</p>
                </div>
                <br>
            </div>
        </div>
        <br><br>
    </section>   

app/views/beta/show.html.erb
<div class="container">

	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Name:</strong>
	  <%= @betum.name %>
	</p>

	<p>
	  <strong>Email:</strong>
	  <%= @betum.email %>
	</p>

	<p>
	  <strong>Expected number listeners:</strong>
	  <%= @betum.expected_number_listeners %>
	</p>

	<p>
	  <strong>What would you do?</strong>
	  <%= @betum.plan %>
	</p>

	<%= link_to 'Edit', edit_betum_path(@betum) %> |
	<%= link_to 'Back', root_path %>

</div>

<br><br>

    <section class="success" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                 <!-- <h2>About</h2> -->
                  <br>
                     <%= image_tag("Visualizer.png", class: "img-responsive middle") %>
                      <h2 style="color: white;">Why Storyboard?</h2> 
                     <hr class="star-light">
                </div>

                <div class="col-md-6">
                     <h2><b>Podcasting for Teams</b></h2> <p>25% of Americans are now regularly listening to podcasts. However, teams and companies still largely communicate over email, where competition for attention is fierce. Want to make a podcast for your team but keep it private? Storyboard makes this easy.</p>
                </div>
                <div class="col-md-6">
                  <h2><b>Easy Listening</b></h2>
                    <p>For your listeners, they will simply download the Storyboard App after receiving a verification code when you register. After we confirm the listener, they can download your episodes to listen in the car, on a flight, or wherever they enjoy listening to podcasts.</p>
                </div>
                <br>
            </div>
        </div>
        <br><br>
    </section>  

    <!-- Reddit Conversion Pixel -->
<script>
var now=Date.now();var i=new Image();i.src="https://alb.reddit.com/snoo.gif?q=CAAHAAABAAoACQAAAAAAmG_bAA==&s=8UGoitauuGLN3-RB5IaXFtfUclHqr-yBDjs-mMzxaFE=&ts="+now;
</script>
<noscript>
<img height="1" width="1" style="display:none"
src="https://alb.reddit.com/snoo.gif?q=CAAHAAABAAoACQAAAAAAmG_bAA==&s=8UGoitauuGLN3-RB5IaXFtfUclHqr-yBDjs-mMzxaFE="/>
</noscript>
<!-- DO NOT MODIFY -->
<!-- End Reddit Conversion Pixel -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Storyboard - Podcasts for Teams</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #e3f2fd;">

  <%= link_to image_tag("storyboard_transparent.png", alt: "Brand"), root_path, :class=>'navbar-brand', :size => '260x180' %>

  <div class="content-to-hide">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">

      <span class="navbar-toggler-icon"></span>
    </button>
   </div>
  <!--
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="#">Features</a>
      <a class="nav-item nav-link" href="#">Pricing</a>
      <a class="nav-item nav-link disabled" href="#">Disabled</a>
    </div>
  </div>
  --> 
</nav>

<%= yield %>

    <div id="footer">
    <b><a href="http://www.twitter.com/trystoryboard">Twitter: @TryStoryboard</a></b>
    <b><p>E: JP @ fearthewave.com</p></b>
    </div>
</body>
</html>

app/views/pages/home.html.erb
<div class="container">

<br>

  <div class="jumbotron">

  <div class="row">
    <div class="col-8">
        <h1 class="display-4"><b>Introducing Storyboard</b></h1>
        <h2>Private Audio, Just for Teams</h2>
        <p class="lead">Storyboard is the first mobile app that allows companies, teams, and organizations to use the power of podcasting, just for their internal audiences.</p> <br>
         <%= link_to "Beta Registration", new_betum_path, class: "btn btn-primary btn-lg" %>
        <p class="lead">Our app - for listening on your iPhone or on the web - will enter beta in December.</p>
        <hr class="my-4">
        <p>We're looking for podcasters who want to deliver private episodes to their selected listeners. For the audience, they can easily stream, download, and hear your show on their phone or desktop, with the ease of traditional podcast apps.</p>
        <p>It will be free to test, but I will hope to get feedback from you as I work to improve and launch the app. Please reach out if you're interested.</p>
        <p class="lead">
    </p>
    </div>

    <div class="col-4">
      <div class="content-to-hide">
        <%= link_to image_tag("iphone_screenshot_storyboard.png", alt: "Brand", :class=>'homeimage') %>
      </div>
      
    </div>
    </div>

</div>

</div>

    <section class="success" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                 <!-- <h2>About</h2> -->
                  <br>
                     <%= image_tag("Visualizer.png", class: "img-responsive middle") %>
                      <h2 style="color: white;">Why Storyboard?</h2> 
                     <hr class="star-light">
                </div>

                <div class="col-md-6">
                     <h2><b>Podcasting for Teams</b></h2> <p>25% of Americans are now regularly listening to podcasts. However, teams and companies still largely communicate over email, where competition for attention is fierce. Want to make a podcast for your team but keep it private? Storyboard makes this easy.</p>
                </div>
                <div class="col-md-6">
                  <h2><b>Easy Listening</b></h2>
                    <p>For your listeners, they will simply download the Storyboard App after receiving a verification code when you register. After we confirm the listener, they can download your episodes to listen in the car, on a flight, or wherever they enjoy listening to podcasts.</p>
                </div>
                <br>
            </div>
        </div>
        <br><br>
    </section>   

app/views/pages/privacy.html.erb
<div class="container">

<h2>December 2018 Update:</h2>

<p> In our next version of the app, users will no longer purchase access to content behind the paywall. As a result, we are working with Apple to stop all active subscriptions so you will not be charged again. 

For your knowledge, there will be no more content distributed in this way through the app, beginning with our last post on December 15th. Thank you for your support.</p>

<h1> Privacy Policy </h1>

Storyboard built the Storyboard app as a Freemium app. This SERVICE is provided by Storyboard at no cost and is intended for use as is -- users can subscribe for $2.99 monthly payments that will enable access to bonus content while supporting podcast publishers who share the content through the app. These payments will be handled exclusively through Apple's in-app payments system. 

This page is used to inform website visitors regarding my policies with the collection, use, and disclosure of Personal Information if anyone decided to use my Service.

If you choose to use my Service, then you agree to the collection and use of information in relation to this policy. The Personal Information that I collect is used for providing and improving the Service. I will not use or share your information with anyone except as described in this Privacy Policy.

The terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, which is accessible at Storyboard unless otherwise defined in this Privacy Policy.

<h1> Information Collection and Use </h1>h1> 

For a better experience, while using our Service, I may require you to provide us with certain personally identifiable information. The information that I request is retained on your device and is not collected by me in any way

The app does use third party services that may collect information used to identify you.

Link to privacy policy of third party service providers used by the app

I want to inform you that whenever you use my Service, in a case of an error in the app I collect data and information (through third party products) on your phone called Log Data. This Log Data may include information such as your device Internet Protocol (“IP”) address, device name, operating system version, the configuration of the app when utilizing my Service, the time and date of your use of the Service, and other statistics.

<h1> Cookies </h1>

Cookies are files with a small amount of data that are commonly used as anonymous unique identifiers. These are sent to your browser from the websites that you visit and are stored on your device's internal memory.

This Service does not use these “cookies” explicitly. However, the app may use third party code and libraries that use “cookies” to collect information and improve their services. You have the option to either accept or refuse these cookies and know when a cookie is being sent to your device. If you choose to refuse our cookies, you may not be able to use some portions of this Service.

<h1> Service Providers </h1>

I may employ third-party companies and individuals due to the following reasons:

To facilitate our Service;
To provide the Service on our behalf;
To perform Service-related services; or
To assist us in analyzing how our Service is used.
I want to inform users of this Service that these third parties have access to your Personal Information. The reason is to perform the tasks assigned to them on our behalf. However, they are obligated not to disclose or use the information for any other purpose.

<h1> Security </h1>

I value your trust in providing us your Personal Information, thus we are striving to use commercially acceptable means of protecting it. But remember that no method of transmission over the internet, or method of electronic storage is 100% secure and reliable, and I cannot guarantee its absolute security.

<h1> Links to Other Sites </h1>

This Service may contain links to other sites. If you click on a third-party link, you will be directed to that site. Note that these external sites are not operated by me. Therefore, I strongly advise you to review the Privacy Policy of these websites. I have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.

<h1> Children’s Privacy </h1>

These Services do not address anyone under the age of 13. I do not knowingly collect personally identifiable information from children under 13. In the case I discover that a child under 13 has provided me with personal information, I immediately delete this from our servers. If you are a parent or guardian and you are aware that your child has provided us with personal information, please contact me so that I will be able to do necessary actions.

<h1> Changes to This Privacy Policy </h1>

I may update our Privacy Policy from time to time. Thus, you are advised to review this page periodically for any changes. I will notify you of any changes by posting the new Privacy Policy on this page. These changes are effective immediately after they are posted on this page.

<h1> Contact Us </h1>

If you have any questions or suggestions about my Privacy Policy, do not hesitate to contact me at JP @ Fearthewave.com or on Twitter @StoryboardApp_.

</div> 